# Generated by Django 5.0 on 2023-12-06 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_userconfirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='AUTH_STATUS',
            new_name='auth_status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='AUTH_TYPE',
            new_name='auth_type',
        ),
    ]
